#############################################################################
# Generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#  Mar 18, 2026 10:48:47 AM CDT  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


#######  Default Fonts ########
set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkTooltipFont
set vTcl(actual_gui_font_tooltip_name)  TkTooltipFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) white
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) Relative
set vTcl(mode) Relative
set vTcl(project_theme) page-dark



proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base

############ toplevel.wgt #############################
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -borderwidth 0 -menu $top.m50 -relief flat -background black -container 0 -height 0 \
        -highlightbackground black -highlightcolor white \
        -highlightthickness 0 -padx 0 -pady 0 -takefocus 0 -width 0 
    wm focusmodel $top passive
    wm geometry $top 717x580+574+300
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Rei & Ash toolkit"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "windowtitle" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
# add aa target = .top1.m50, basename = $top.m50
    menu "$top.m50" \
        -activebackground #d9d9d9 -activeborderwidth 1 \
        -activeforeground black -background black -borderwidth 1 \
        -disabledforeground #3f3f3f -font "TkDefaultFont" -foreground white \
        -relief raised -selectcolor #000000 -takefocus 0 -tearoff 0 \
        -type normal 
# add first menu widget
    entry "$top.ent56" \
        -background black -borderwidth 1 -cursor xterm \
        -disabledbackground #d9d9d9 -disabledforeground #3f3f3f \
        -exportselection 0 -font "TkFixedFont" -foreground white \
        -highlightbackground black -highlightcolor white \
        -highlightthickness 1 -insertbackground white -insertborderwidth 0 \
        -insertofftime 300 -insertontime 600 -insertwidth 2 -justify left \
        -readonlybackground #d9d9d9 -relief sunken -selectbackground #d9d9d9 \
        -selectborderwidth 0 -selectforeground black -state normal \
        -textvariable "target" -validate none -width 216 
    vTcl:DefineAlias "$top.ent56" "target" vTcl:WidgetProc "windowtitle" 1
    vTcl:copy_lock $top.ent56
    label "$top.lab50" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background black -borderwidth 1 -compound left -cursor fleur \
        -disabledforeground #3f3f3f -font "-family {Quicksand} -size 14" \
        -foreground white -height 0 -highlightbackground black \
        -highlightcolor white -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "TARGET/IP" \
        -underline -1 -width 299 -wraplength 0 
    vTcl:DefineAlias "$top.lab50" "targetlabel" vTcl:WidgetProc "windowtitle" 1
    vTcl:copy_lock $top.lab50
    label "$top.lab49" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background black -borderwidth 1 -compound left -cursor fleur \
        -disabledforeground #3f3f3f -font "-family {Quicksand} -size 14" \
        -foreground white -height 0 -highlightbackground black \
        -highlightcolor white -highlightthickness 0 -justify center -padx 1 \
        -pady 1 -relief flat -state normal -takefocus 0 -text "REI Recon" \
        -underline -1 -width 128 -wraplength 0 
    vTcl:DefineAlias "$top.lab49" "title" vTcl:WidgetProc "windowtitle" 1
    vTcl:copy_lock $top.lab49
    menubutton "$top.men55" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background black -borderwidth 1 -direction below \
        -disabledforeground #3f3f3f -font "-family {Quicksand} -size 14" \
        -foreground white -height 39 -highlightbackground black \
        -highlightcolor white -highlightthickness 0 -indicatoron 1 \
        -justify center -menu $top.men55.m -padx 5 -pady 4 -relief raised -compound left \
        -state normal -takefocus 0 -text "EXPLOITS" -underline -1 -width 197 \
        -wraplength 0 
    vTcl:DefineAlias "$top.men55" "exploitsmenu" vTcl:WidgetProc "windowtitle" 1
# add aa target = .top1.men55.m, basename = $top.men55.m
    menu "$top.men55.m" \
        -activebackground #ececec -activeborderwidth 1 \
        -activeforeground black -background black -borderwidth 1 \
        -cursor arrow -disabledforeground #3f3f3f -font "TkMenuFont" \
        -foreground white -relief raised -selectcolor #000000 -takefocus 0 \
        -tearoff 0 -type normal 
# add first menu widget
    vTcl:copy_lock $top.men55
    menubutton "$top.men51" \
        -activebackground #d9d9d9 -activeforeground black -anchor w \
        -background black -borderwidth 1 -cursor fleur -direction below \
        -disabledforeground #3f3f3f -font "-family {Quicksand} -size 14" \
        -foreground white -height 39 -highlightbackground black \
        -highlightcolor white -highlightthickness 0 -indicatoron 1 \
        -justify center -menu $top.men51.m -padx 5 -pady 4 -relief raised -compound left \
        -state normal -takefocus 0 -text "RECON TOOLS" -underline -1 \
        -width 198 -wraplength 0 
    vTcl:DefineAlias "$top.men51" "reconmenu" vTcl:WidgetProc "windowtitle" 1
# add aa target = .top1.men51.m, basename = $top.men51.m
    menu "$top.men51.m" \
        -activebackground #ececec -activeborderwidth 1 \
        -activeforeground black -background black -borderwidth 1 \
        -cursor arrow -disabledforeground #3f3f3f -font "TkMenuFont" \
        -foreground white -relief raised -selectcolor #000000 -takefocus 0 \
        -tearoff 0 -type normal 
# add first menu widget
    $top.men51.m add command \
        -command "#dumpster()" -compound left -font "TkMenuFont" \
        -label "DNS Dumpster (API Required)" 
# add 5a
    $top.men51.m add command \
        -command "#processdns()" -compound left -font "TkMenuFont" \
        -label "NMAP (DNS)" 
# add 5a
    $top.men51.m add command \
        -command "#processversion()" -compound left -font "TkMenuFont" \
        -label "NMAP (Version)" 
# add 5a
    $top.men51.m add command \
        -command "#processtopports()" -compound left -font "TkMenuFont" \
        -label "NMAP (Top Ports)" 
# add 5a
    $top.men51.m add command \
        -command "#processos()" -compound left -font "TkMenuFont" \
        -label "NMAP (OS)" 
# add 5a
    $top.men51.m add command \
        -command "#vulnscanmodule()" -compound left -font "TkMenuFont" \
        -label "NMAP (CVE Scan)" 
# add 5a
    $top.men51.m add command \
        -command "#xsstest()" -compound left -font "TkMenuFont" \
        -label "XSS Detection" 
# add 5a
    $top.men51.m add command \
        -command "#wpscanmodule()" -compound left -font "TkMenuFont" \
        -label "WPScan (API required)" 
# add 5a
    $top.men51.m add command \
        -command "#nucleitest()" -compound left -font "TkMenuFont" \
        -label "Nuclei" 
# add 5a
    $top.men51.m add command \
        -command "#gobustertest()" -compound left -font "TkMenuFont" \
        -label "Gobuster" 
# add 5a
    vTcl:copy_lock $top.men51
    label "$top.lab52" \
        -activebackground #d9d9d9 -activeforeground black -anchor center \
        -background #2d2d2d -borderwidth 1 -compound left \
        -disabledforeground #3f3f3f -font "TkDefaultFont" -foreground white \
        -height 0 -highlightbackground black -highlightcolor white \
        -highlightthickness 0 -justify center -padx 1 -pady 1 -relief flat \
        -state normal -takefocus 0 -text "Awaiting instructions" \
        -underline -1 -width 681 -wraplength 0 
    vTcl:DefineAlias "$top.lab52" "results" vTcl:WidgetProc "windowtitle" 1
    vTcl:copy_lock $top.lab52
    ###################
    # SETTING GEOMETRY
    ###################
# add p1 basename = $top.ent56
    place $top.ent56 \
        -in $top -x 0 -relx 0.363 -y 0 -rely 0.345 -width 216 -relwidth 0 \
        -height 23 -relheight 0 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab50
    place $top.lab50 \
        -in $top -x 0 -relx 0.307 -y 0 -rely 0.276 -width 0 -relwidth 0.417 \
        -height 0 -relheight 0.04 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab49
    place $top.lab49 \
        -in $top -x 0 -relx 0.432 -y 0 -rely 0.086 -width 0 -relwidth 0.18 \
        -height 0 -relheight 0.109 -anchor nw -bordermode ignore 
# add p1 basename = $top.men55
    place $top.men55 \
        -in $top -x 0 -relx 0.697 -y 0 -rely 0.328 -width 0 -relwidth 0.276 \
        -height 0 -relheight 0.067 -anchor nw -bordermode ignore 
# add p1 basename = $top.men51
    place $top.men51 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.328 -width 0 -relwidth 0.276 \
        -height 0 -relheight 0.067 -anchor nw -bordermode ignore 
# add p1 basename = $top.lab52
    place $top.lab52 \
        -in $top -x 0 -relx 0.028 -y 0 -rely 0.431 -width 0 -relwidth 0.95 \
        -height 0 -relheight 0.505 -anchor nw -bordermode ignore 

############# Spot ttt ##############################

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

