#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Mar 18, 2026 10:07:51 AM CDT  platform: Linux

import os.path
import tkinter as tk
from tkinter import messagebox, filedialog

_location = os.path.dirname(__file__)

import gui_support

_bgcolor = 'black'
_fgcolor = 'white'
_tabfg1 = 'black'
_tabfg2 = 'white'
_bgmode = 'light'
_tabbg1 = '#d9d9d9'
_tabbg2 = 'gray40'


class windowtitle:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("717x580+574+300")
        top.minsize(1, 1)
        top.maxsize(1905, 1050)
        top.resizable(1, 1)
        top.title("Rei & Ash toolkit")
        top.configure(background="black")
        top.configure(highlightbackground="black")
        top.configure(highlightcolor="white")

        self.top = top
        self.target = tk.StringVar()
        self.target.set('Entry')
        self.current_operation = None

        self.menubar = tk.Menu(top, font="TkMenuFont", bg='black', fg='white')
        top.configure(menu=self.menubar)

        # Add File menu
        self.file_menu = tk.Menu(self.menubar, tearoff=0, background=_bgcolor, foreground=_fgcolor)
        self.menubar.add_cascade(label="File", menu=self.file_menu)
        self.file_menu.add_command(label="Save Results", command=self.save_results)
        self.file_menu.add_command(label="Clear Results", command=self.clear_results)
        self.file_menu.add_separator()
        self.file_menu.add_command(label="Exit", command=top.destroy)

        # Add Configuration menu
        self.config_menu = tk.Menu(self.menubar, tearoff=0, background=_bgcolor, foreground=_fgcolor)
        self.menubar.add_cascade(label="Configuration", menu=self.config_menu)
        self.config_menu.add_command(label="API Keys", command=self.show_config_dialog)

        # Add Help menu
        self.help_menu = tk.Menu(self.menubar, tearoff=0, background=_bgcolor, foreground=_fgcolor)
        self.menubar.add_cascade(label="Help", menu=self.help_menu)
        self.help_menu.add_command(label="About", command=self.show_about_dialog)

        ########### start #######################
        ########### end #######################

        self.target_entry = tk.Entry(self.top)
        self.target_entry.place(relx=0.363, rely=0.345, height=23, relwidth=0.301)
        self.target_entry.configure(background="black")
        self.target_entry.configure(disabledforeground="#3f3f3f")
        self.target_entry.configure(exportselection="0")
        self.target_entry.configure(font="TkFixedFont")
        self.target_entry.configure(foreground="white")
        self.target_entry.configure(highlightbackground="black")
        self.target_entry.configure(highlightcolor="white")
        self.target_entry.configure(insertbackground="white")
        self.target_entry.configure(selectbackground="#d9d9d9")
        self.target_entry.configure(textvariable=self.target)

        self.targetlabel = tk.Label(self.top)
        self.targetlabel.place(relx=0.307, rely=0.276, height=23, width=299)
        self.targetlabel.configure(activebackground="#d9d9d9")
        self.targetlabel.configure(background="black")
        self.targetlabel.configure(compound='left')
        self.targetlabel.configure(cursor="fleur")
        self.targetlabel.configure(disabledforeground="#3f3f3f")
        self.targetlabel.configure(font="-family {Quicksand} -size 14")
        self.targetlabel.configure(foreground="white")
        self.targetlabel.configure(highlightbackground="black")
        self.targetlabel.configure(highlightcolor="white")
        self.targetlabel.configure(text='''TARGET/IP''')

        self.title = tk.Label(self.top)
        self.title.place(relx=0.432, rely=0.086, height=63, width=129)
        self.title.configure(activebackground="#d9d9d9")
        self.title.configure(background="black")
        self.title.configure(compound='left')
        self.title.configure(cursor="fleur")
        self.title.configure(disabledforeground="#3f3f3f")
        self.title.configure(font="-family {Quicksand} -size 14")
        self.title.configure(foreground="white")
        self.title.configure(highlightbackground="black")
        self.title.configure(highlightcolor="white")
        self.title.configure(text='''REI Recon''')

        self.exploitsmenu = tk.Menubutton(self.top)
        self.exploitsmenu.place(relx=0.697, rely=0.328, relheight=0.067
                                , relwidth=0.276)
        self.men55_m = tk.Menu(self.exploitsmenu, tearoff=0, background=_bgcolor, foreground=_fgcolor)
        self.exploitsmenu.configure(activebackground="#d9d9d9")
        self.exploitsmenu.configure(anchor='w')
        self.exploitsmenu.configure(background="black")
        self.exploitsmenu.configure(disabledforeground="#3f3f3f")
        self.exploitsmenu.configure(font="-family {Quicksand} -size 14")
        self.exploitsmenu.configure(foreground="white")
        self.exploitsmenu.configure(highlightbackground="black")
        self.exploitsmenu.configure(highlightcolor="white")
        self.exploitsmenu.configure(indicatoron="1")
        self.exploitsmenu.configure(menu=self.men55_m)
        self.exploitsmenu.configure(padx="5")
        self.exploitsmenu.configure(pady="4")
        self.exploitsmenu.configure(relief="raised")
        self.exploitsmenu.configure(compound='left')
        self.exploitsmenu.configure(text='''EXPLOITS''')

        # Create a Text widget for results instead of a Label
        self.results = tk.Text(self.top, wrap=tk.WORD, state=tk.DISABLED)
        self.results.place(relx=0.028, rely=0.431, height=293, width=681)
        self.results.configure(background="#2d2d2d")
        self.results.configure(foreground="white")
        self.results.configure(highlightbackground="black")
        self.results.configure(highlightcolor="white")
        self.results.insert(tk.END, "Awaiting instructions")

        self.reconmenu = tk.Menubutton(self.top)
        self.reconmenu.place(relx=0.028, rely=0.328, relheight=0.067
                             , relwidth=0.276)
        self.men51_m = tk.Menu(self.reconmenu, tearoff=0, background=_bgcolor, foreground=_fgcolor)
        self.reconmenu.configure(activebackground="#d9d9d9")
        self.reconmenu.configure(anchor='w')
        self.reconmenu.configure(background="black")
        self.reconmenu.configure(cursor="fleur")
        self.reconmenu.configure(disabledforeground="#3f3f3f")
        self.reconmenu.configure(font="-family {Quicksand} -size 14")
        self.reconmenu.configure(foreground="white")
        self.reconmenu.configure(highlightbackground="black")
        self.reconmenu.configure(highlightcolor="white")
        self.reconmenu.configure(indicatoron="1")
        self.reconmenu.configure(menu=self.men51_m)
        self.reconmenu.configure(padx="5")
        self.reconmenu.configure(pady="4")
        self.reconmenu.configure(relief="raised")
        self.reconmenu.configure(compound='left')
        self.reconmenu.configure(text='''RECON TOOLS''')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.dumpster, self.target.get(), self)
                                 , compound='left', font="TkMenuFont"
                                 , label='DNS Dumpster (API Required)')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.processdns, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='NMAP (DNS)')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.processversion, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='NMAP (Version)')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.processtopports, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='NMAP (Top Ports)')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.processos, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='NMAP (OS)')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.vulnscanmodule, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='NMAP (CVE Scan)')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.xsstest, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='XSS Detection')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.wpscanmodule, self.target.get(), self)
                                 , compound='left', font="TkMenuFont"
                                 , label='WPScan (API required)')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.nucleitest, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='Nuclei')
        self.men51_m.add_command(command=lambda: self.run_with_cancel(gui_support.gobustertest, self.target.get(), self)
                                 , compound='left', font="TkMenuFont", label='Gobuster')

        # Add a cancel button
        self.cancel_button = tk.Button(self.top, text="Cancel Operation", command=self.cancel_operation)
        self.cancel_button.place(relx=0.028, rely=0.9, height=23, width=681)
        self.cancel_button.configure(background="#2d2d2d")
        self.cancel_button.configure(foreground="white")
        self.cancel_button.configure(state=tk.DISABLED)

        # Add a status bar
        self.status_var = tk.StringVar()
        self.status_var.set("Ready")
        self.status_bar = tk.Label(self.top, textvariable=self.status_var, bd=1, relief=tk.SUNKEN, anchor=tk.W)
        self.status_bar.place(relx=0.028, rely=0.95, height=23, width=681)
        self.status_bar.configure(background="#2d2d2d")
        self.status_bar.configure(foreground="white")

    def run_with_cancel(self, func, *args):
        """Run a function with cancellation support"""
        self.current_operation = gui_support.thread_manager.start_thread(func, *args)
        self.cancel_button.configure(state=tk.NORMAL)
        self.status_var.set("Operation in progress...")

    def cancel_operation(self):
        """Cancel the current operation"""
        if self.current_operation:
            self.current_operation.cancel()
            self.current_operation = None
        self.cancel_button.configure(state=tk.DISABLED)
        self.status_var.set("Operation cancelled")
        gui_support.append_results(self, "\nOperation cancelled by user.\n")

    def save_results(self):
        """Save the results to a file"""
        content = self.results.get(1.0, tk.END)
        if content.strip():
            file_path = filedialog.asksaveasfilename(
                defaultextension=".txt",
                filetypes=[("Text files", "*.txt"), ("All files", "*.*")]
            )
            if file_path:
                try:
                    with open(file_path, 'w') as file:
                        file.write(content)
                    messagebox.showinfo("Success", "Results saved successfully!")
                except Exception as e:
                    messagebox.showerror("Error", f"Failed to save results: {str(e)}")
        else:
            messagebox.showwarning("Warning", "No results to save!")

    def clear_results(self):
        """Clear the results text widget"""
        self.results.config(state=tk.NORMAL)
        self.results.delete(1.0, tk.END)
        self.results.config(state=tk.DISABLED)
        self.status_var.set("Results cleared")

    def show_config_dialog(self):
        """Show the configuration dialog for API keys"""
        dialog = tk.Toplevel(self.top)
        dialog.title("API Configuration")
        dialog.geometry("400x200")
        dialog.configure(background="black")
        dialog.resizable(False, False)

        # Center the dialog
        dialog.transient(self.top)
        dialog.grab_set()

        # DNSdumpster API Key
        tk.Label(dialog, text="DNSdumpster API Key:", background="black", foreground="white").pack(pady=5)
        dns_entry = tk.Entry(dialog, width=50, bg="#2d2d2d", fg="white")
        dns_entry.insert(0, gui_support.dnsdumpsterapi)
        dns_entry.pack(pady=5)

        # WPScan API Key
        tk.Label(dialog, text="WPScan API Key:", background="black", foreground="white").pack(pady=5)
        wpscan_entry = tk.Entry(dialog, width=50, bg="#2d2d2d", fg="white")
        wpscan_entry.insert(0, gui_support.wpscanapi)
        wpscan_entry.pack(pady=5)

        def save_config():
            """Save the configuration to keys.py"""
            try:
                with open('keys.py', 'w') as f:
                    f.write(f"dnsdumpsterapi = '{dns_entry.get()}'\n")
                    f.write(f"wpscanapi = '{wpscan_entry.get()}'\n")
                
                # Update the global variables in gui_support
                gui_support.dnsdumpsterapi = dns_entry.get()
                gui_support.wpscanapi = wpscan_entry.get()
                
                messagebox.showinfo("Success", "API keys saved successfully!")
                dialog.destroy()
            except Exception as e:
                messagebox.showerror("Error", f"Failed to save API keys: {str(e)}")

        # Save button
        tk.Button(dialog, text="Save", command=save_config, bg="#2d2d2d", fg="white").pack(pady=10)

    def show_about_dialog(self):
        """Show the about dialog"""
        about_text = """REI & Ash Toolkit v3.0

A comprehensive security reconnaissance toolkit
for penetration testers and security professionals.

Features:
- DNS enumeration
- Port scanning
- Vulnerability assessment
- Web application testing

Created with PAGE v8.1 and Tkinter"""
        
        messagebox.showinfo("About REI & Ash Toolkit", about_text)


def start_up():
    gui_support.main()


if __name__ == '__main__':
    gui_support.main()