#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 8.1
#  in conjunction with Tcl version 8.6
#    Mar 16, 2026 10:55:59 PM CDT  platform: Linux

import subprocess
import threading
import tkinter as tk
import queue
import re
import logging
import datetime
import time

import nmap3
import requests

from keys import *

# Variables and API keys
dnsdumpsterapi = ''
wpscanapi = ''

nmap = nmap3.Nmap()

import gui

_debug = True  # False to eliminate debug printing from callback functions.

# Configure logging
logging.basicConfig(
    filename='app.log',
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)

# Maximum lines to display in the results widget
MAX_LINES = 1000

# Thread management classes
class CancellableThread:
    def __init__(self, target_func, *args):
        self._target = target_func
        self._args = args
        self._cancelled = False
        self._thread = threading.Thread(target=self._run)
        self._process = None  # For subprocess cancellation
    
    def _run(self):
        try:
            self._target(*self._args)
        except Exception as e:
            if not self._cancelled:
                log_message('error', f"Thread error: {str(e)}")
    
    def start(self):
        self._thread.start()
        return self
    
    def cancel(self):
        self._cancelled = True
        # If there's a subprocess, terminate it
        if self._process and self._process.poll() is None:
            self._process.terminate()
    
    def join(self, timeout=None):
        return self._thread.join(timeout)
    
    def is_alive(self):
        return self._thread.is_alive()
    
    def set_process(self, process):
        """Set the subprocess for cancellation"""
        self._process = process

class ThreadManager:
    def __init__(self):
        self.active_threads = []
    
    def start_thread(self, target_func, *args):
        # Clean up finished threads
        self.cleanup_finished_threads()
        
        thread = CancellableThread(target_func, *args)
        thread.start()
        self.active_threads.append(thread)
        return thread
    
    def cleanup_finished_threads(self):
        self.active_threads = [t for t in self.active_threads if t.is_alive()]

# Initialize the thread manager
thread_manager = ThreadManager()

def log_message(level, message):
    """Log a message with timestamp"""
    if level == 'error':
        logging.error(message)
    elif level == 'warning':
        logging.warning(message)
    else:
        logging.info(message)

def validate_target(target):
    """Validate the target input"""
    if not target or not target.strip():
        return False, "Empty target provided"
    
    # Remove protocol if present
    if target.startswith('http://') or target.startswith('https://'):
        target = target.split('://', 1)[1]
    
    # Basic domain/IP validation
    domain_pattern = r'^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?\.)+[a-zA-Z]{2,}$'
    ip_pattern = r'^(?:[0-9]{1,3}\.){3}[0-9]{1,3}$'
    
    if not (re.match(domain_pattern, target) or re.match(ip_pattern, target)):
        return False, "Invalid domain or IP format"
    
    return True, target.strip()

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol('WM_DELETE_WINDOW', root.destroy)
    # Creates a toplevel widget.
    global _top1, _w1
    _top1 = root
    _w1 = gui.windowtitle(_top1)
    root.mainloop()


def update_results(gui_instance, text):
    """Thread-safe helper function to update the results text widget"""

    def _update():
        gui_instance.results.config(state=tk.NORMAL)
        gui_instance.results.delete(1.0, tk.END)
        gui_instance.results.insert(tk.END, text)
        gui_instance.results.config(state=tk.DISABLED)
        gui_instance.status_var.set("Ready")

    # Schedule the update to run in the main thread
    gui_instance.top.after(0, _update)


def append_results(gui_instance, text):
    """Thread-safe helper function to append text to the results text widget"""
    
    def _append():
        gui_instance.results.config(state=tk.NORMAL)
        gui_instance.results.insert(tk.END, text)
        
        # Limit the number of lines to prevent memory issues
        line_count = int(gui_instance.results.index('end-1c').split('.')[0])
        if line_count > MAX_LINES:
            # Remove the oldest lines
            delete_count = line_count - MAX_LINES
            gui_instance.results.delete(1.0, f"{delete_count}.0")
        
        gui_instance.results.see(tk.END)
        gui_instance.results.config(state=tk.DISABLED)

    # Schedule the update to run in the main thread
    gui_instance.top.after(0, _append)


def dumpster(target, gui_instance):
    update_results(gui_instance, 'DNS Dumpster (API Required) module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        if dnsdumpsterapi == '':
            update_results(gui_instance, '[+] DNSdumpster API key missing, skipping test.')
            return

        try:
            url = f'https://api.dnsdumpster.com/domain/{clean_target}'
            headers = {'X-Api-Key': dnsdumpsterapi}
            
            # Add timeout to prevent hanging
            response = requests.get(url, headers=headers, timeout=30)
            
            if response.status_code == 200:
                try:
                    data = response.json()
                    
                    # Build the complete result text before updating the GUI
                    result_text = '\nA records:\n'
                    if 'a' in data and data['a']:
                        for item in data['a']:
                            result_text += '[+] Host:' + item['host'] + '\n'
                            for ip in item['ips']:
                                result_text += '[+] IP: ' + ip['ip'] + '\n'
                                result_text += '[+] ASN_NAME:' + ip['asn_name'] + '\n'
                                result_text += '[+] Country:' + ip['country'] + '\n'
                                result_text += '[+] City:' + ip.get('city', 'Not found') + '\n'
                                result_text += '-----------------------\n'
                    else:
                        result_text += 'No A records found.\n'
                    
                    result_text += '\nMX records:\n'
                    if 'mx' in data and data['mx']:
                        for item in data['mx']:
                            result_text += '[+] Host:' + item['host'] + '\n'
                            for ip in item['ips']:
                                result_text += '[+] IP: ' + ip['ip'] + '\n'
                                result_text += '[+] ASN_NAME:' + ip['asn_name'] + '\n'
                                result_text += '[+] Country:' + ip['country'] + '\n'
                                result_text += '[+] City:' + ip.get('city', 'Not found') + '\n'
                                result_text += '-----------------------\n'
                    else:
                        result_text += 'No MX records found.\n'
                    
                    result_text += '\nNS records:\n'
                    if 'ns' in data and data['ns']:
                        for item in data['ns']:
                            result_text += '[+] Host:' + item['host'] + '\n'
                            for ip in item['ips']:
                                result_text += '[+] IP: ' + ip['ip'] + '\n'
                                result_text += '[+] ASN_NAME:' + ip['asn_name'] + '\n'
                                result_text += '[+] Country:' + ip['country'] + '\n'
                                result_text += '[+] City:' + ip.get('city', 'Not found') + '\n'
                                result_text += '-----------------------\n'
                    else:
                        result_text += 'No NS records found.\n'
                    
                    # Update the GUI with the complete result
                    update_results(gui_instance, result_text)
                except ValueError as e:
                    update_results(gui_instance, f'[+] Error parsing JSON response: {str(e)}')
            elif response.status_code == 401:
                update_results(gui_instance, '[+] Error: Invalid API key for DNSdumpster')
            elif response.status_code == 429:
                update_results(gui_instance, '[+] Error: Rate limit exceeded for DNSdumpster API')
            else:
                update_results(gui_instance, f'[+] Error: HTTP {response.status_code} - {response.text}')
        except requests.exceptions.Timeout:
            update_results(gui_instance, '[+] Error: Request to DNSdumpster timed out')
        except requests.exceptions.ConnectionError:
            update_results(gui_instance, '[+] Error: Could not connect to DNSdumpster')
        except Exception as e:
            error_msg = f'Error in dumpster: {str(e)}'
            log_message('error', error_msg)
            update_results(gui_instance, f'[+] Unexpected error: {str(e)}')

    thread_manager.start_thread(_worker)


def processdns(target, gui_instance):
    update_results(gui_instance, 'NMAP (DNS) module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        try:
            dns_results = nmap.nmap_dns_brute_script(clean_target)
            result_text = ""
            for item in dns_results:
                result_text += '\n[+] Hostname: ' + item['hostname'] + '\n'
                result_text += '[+] IP Address: ' + item['address'] + '\n'
                result_text += '-----------------------\n'
            update_results(gui_instance, result_text)
        except Exception as e:
            error_msg = f'Error in processdns: {str(e)}'
            log_message('error', error_msg)
            update_results(gui_instance, f'Error: {str(e)}')

    thread_manager.start_thread(_worker)


def processversion(target, gui_instance):
    update_results(gui_instance, 'NMAP (Version) module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        try:
            version_results = nmap.nmap_version_detection(clean_target)
            ip_address = next(iter(version_results))
            version = version_results[ip_address]
            result_text = ""
            for port in version['ports']:
                result_text += '\n[+] Protocol: ' + port['protocol'] + '\n'
                result_text += '[+] Port: ' + port['portid'] + '\n'
                result_text += '[+] State: ' + port['state'] + '\n'
                result_text += '[+] Name: ' + port['service']['name'] + '\n'
                result_text += '-----------------------\n'
            update_results(gui_instance, result_text)
        except Exception as e:
            error_msg = f'Error in processversion: {str(e)}'
            log_message('error', error_msg)
            update_results(gui_instance, f'Error: {str(e)}')

    thread_manager.start_thread(_worker)


def processtopports(target, gui_instance):
    update_results(gui_instance, 'NMAP (Top Ports) module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        try:
            top_ports = nmap.scan_top_ports(clean_target)
            ports_results = next(iter(top_ports))
            port = top_ports[ports_results]
            result_text = ""
            for port in port['ports']:
                result_text += '\n[+] Port: ' + port['portid'] + '\n'
                result_text += '[+] Protocol: ' + port['protocol'] + '\n'
                result_text += '[+] State: ' + port['state'] + '\n'
                result_text += '[+] Service: ' + port['service']['name'] + '\n'
                result_text += '-----------------------\n'
            update_results(gui_instance, result_text)
        except Exception as e:
            error_msg = f'Error in processtopports: {str(e)}'
            log_message('error', error_msg)
            update_results(gui_instance, f'Error: {str(e)}')

    thread_manager.start_thread(_worker)


def processos(target, gui_instance):
    update_results(gui_instance, 'NMAP (OS) module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        try:
            os_results = nmap.nmap_os_detection(clean_target)
            ip_address = next(iter(os_results))
            os_version = os_results[ip_address]
            result_text = ""
            for item in os_version['osmatch']:
                result_text += '\n[+] OS: ' + item['name'] + '\n'
                result_text += '[+] Family: ' + item['osclass']['osfamily'] + '\n'
                result_text += '[+] Type: ' + item['osclass']['type'] + '\n'
                result_text += '[+] Generation: ' + item['osclass']['osgen'] + '\n'
                result_text += '[+] Accuracy: ' + item['accuracy'] + '\n'
                result_text += '-----------------------\n'
            update_results(gui_instance, result_text)
        except Exception as e:
            error_msg = f'Error in processos: {str(e)}'
            log_message('error', error_msg)
            update_results(gui_instance, f'Error: {str(e)}')

    thread_manager.start_thread(_worker)


def xsstest(target, gui_instance):
    update_results(gui_instance, 'XSS Detection module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        try:
            url = f'https://www.{clean_target}/search?'
            payloads = ['<script>alert(1)</script>', '"><img src=x onerror=alert(1)>']
            result_text = ""
            for payload in payloads:
                params = {'q': payload}
                try:
                    r = requests.get(url, params=params, timeout=10)
                    if payload in r.text:
                        result_text += f'\n[XSS] Payload reflected: {payload}\n'
                    else:
                        result_text += f'\n[XSS] Not vulnerable to payload: {payload}\n'
                except requests.exceptions.RequestException as e:
                    result_text += f'\n[XSS] Error testing payload {payload}: {str(e)}\n'
            update_results(gui_instance, result_text)
        except Exception as e:
            error_msg = f'Error in xsstest: {str(e)}'
            log_message('error', error_msg)
            update_results(gui_instance, f'Error: {str(e)}')

    thread_manager.start_thread(_worker)


def run_subprocess_with_live_output(gui_instance, command, filename=None):
    """Run a subprocess command and display output in real-time"""
    process = None
    current_thread = threading.current_thread()
    
    try:
        # Start the subprocess
        process = subprocess.Popen(
            command,
            shell=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            universal_newlines=True,
            bufsize=1
        )
        
        # Store the process in the current thread for cancellation
        if hasattr(current_thread, 'set_process'):
            current_thread.set_process(process)
        
        # Read and display output line by line
        for line in iter(process.stdout.readline, ''):
            if line:  # Skip empty lines
                append_results(gui_instance, line.rstrip() + '\n')
        
        # Wait for the process to complete
        process.stdout.close()
        return_code = process.wait()
        
        if return_code != 0:
            append_results(gui_instance, f"\nCommand exited with code {return_code}\n")
        else:
            if filename:
                append_results(gui_instance, f"\nScan completed. Results saved to {filename}\n")
            else:
                append_results(gui_instance, "\nScan completed.\n")
                
    except Exception as e:
        append_results(gui_instance, f'Error: {str(e)}\n')
        error_msg = f'Error in subprocess: {str(e)}'
        log_message('error', error_msg)
    finally:
        # Ensure the process is terminated
        if process and process.poll() is None:
            process.terminate()
            try:
                process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                process.kill()


def vulnscanmodule(target, gui_instance):
    update_results(gui_instance, 'NMAP (CVE Scan) module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        command = f'nmap --script vuln --script-args mincvss+5.0 {clean_target}'
        run_subprocess_with_live_output(gui_instance, command)
    
    thread_manager.start_thread(_worker)


def wpscanmodule(target, gui_instance):
    update_results(gui_instance, 'WPScan (API required) module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        if wpscanapi == '':
            update_results(gui_instance, '[+] WPScan API key missing, skipping test.')
            return
        
        command = f'wpscan --api-token {wpscanapi} --url {clean_target} --random-user-agent --force'
        run_subprocess_with_live_output(gui_instance, command)
    
    thread_manager.start_thread(_worker)


def nucleitest(target, gui_instance):
    update_results(gui_instance, 'Nuclei module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        filename = f'nuclei_results_{clean_target.replace("/", "_")}.txt'
        command = f'nuclei -u {clean_target} -o {filename}'
        run_subprocess_with_live_output(gui_instance, command, filename)
    
    thread_manager.start_thread(_worker)


def gobustertest(target, gui_instance):
    update_results(gui_instance, 'Gobuster module running, please wait...')
    
    def _worker():
        # Validate input
        is_valid, clean_target = validate_target(target)
        if not is_valid:
            update_results(gui_instance, f'[+] Error: {clean_target}')
            return
        
        # Create a dialog for wordlist input
        def get_wordlist():
            dialog = tk.Toplevel(gui_instance.top)
            dialog.title("Gobuster Configuration")
            dialog.geometry("400x150")
            dialog.configure(background="black")
            dialog.resizable(False, False)
            
            # Center the dialog
            dialog.transient(gui_instance.top)
            dialog.grab_set()
            
            tk.Label(dialog, text="Path to wordlist:", background="black", foreground="white").pack(pady=10)
            
            wordlist_entry = tk.Entry(dialog, width=50, bg="#2d2d2d", fg="white")
            wordlist_entry.pack(pady=5)
            
            result = {"path": None, "cancelled": False}
            
            def browse_wordlist():
                path = filedialog.askopenfilename(
                    title="Select Wordlist File",
                    filetypes=[("Text files", "*.txt"), ("All files", "*.*")]
                )
                if path:
                    wordlist_entry.delete(0, tk.END)
                    wordlist_entry.insert(0, path)
            
            def confirm():
                result["path"] = wordlist_entry.get()
                dialog.destroy()
            
            def cancel():
                result["cancelled"] = True
                dialog.destroy()
            
            tk.Button(dialog, text="Browse", command=browse_wordlist, bg="#2d2d2d", fg="white").pack(pady=5)
            
            button_frame = tk.Frame(dialog, bg="black")
            button_frame.pack(pady=10)
            
            tk.Button(button_frame, text="OK", command=confirm, bg="#2d2d2d", fg="white").pack(side=tk.LEFT, padx=10)
            tk.Button(button_frame, text="Cancel", command=cancel, bg="#2d2d2d", fg="white").pack(side=tk.RIGHT, padx=10)
            
            dialog.wait_window()
            return result
        
        wordlist_info = get_wordlist()
        if wordlist_info["cancelled"] or not wordlist_info["path"]:
            update_results(gui_instance, 'No wordlist provided, skipping test.')
            return
        
        path = wordlist_info["path"]
        filename = f'gobuster_results_{clean_target.replace("/", "_")}.txt'
        command = f'gobuster dir -u {clean_target} -w {path} -o {filename}'
        run_subprocess_with_live_output(gui_instance, command, filename)
    
    thread_manager.start_thread(_worker)


if __name__ == '__main__':
    gui.start_up()